project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: Salary Trends.qmd
        text: "Research"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



