project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: "Salary Trends.qmd"
        text: AI vs Non-AI Salary Trends
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



