<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.547">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-04-17">

<title>Job Market Analysis 2024 - Assignment 3: Machine Learning on Scale</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Job Market Analysis 2024</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./introduction.html"> 
<span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data_cleaning.html"> 
<span class="menu-text">Data Cleaning &amp; Exploration</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda.html"> 
<span class="menu-text">Exploratory Data Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./skill_gap_analysis.html"> 
<span class="menu-text">Skill Gap Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ml_methods.html"> 
<span class="menu-text">ML Methods</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#important-reminder" id="toc-important-reminder" class="nav-link active" data-scroll-target="#important-reminder">Important Reminder</a></li>
  <li><a href="#github-classroom-repository" id="toc-github-classroom-repository" class="nav-link" data-scroll-target="#github-classroom-repository">GitHub Classroom Repository</a>
  <ul class="collapse">
  <li><a href="#clone-the-repository-on-your-ec2-instance" id="toc-clone-the-repository-on-your-ec2-instance" class="nav-link" data-scroll-target="#clone-the-repository-on-your-ec2-instance">Clone the Repository on Your EC2 Instance</a>
  <ul class="collapse">
  <li><a href="#option-1-using-terminal" id="toc-option-1-using-terminal" class="nav-link" data-scroll-target="#option-1-using-terminal">Option 1: Using Terminal</a></li>
  <li><a href="#option-2-using-vs-code-git-source-control" id="toc-option-2-using-vs-code-git-source-control" class="nav-link" data-scroll-target="#option-2-using-vs-code-git-source-control">Option 2: Using VS Code Git Source Control</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#load-the-dataset" id="toc-load-the-dataset" class="nav-link" data-scroll-target="#load-the-dataset"><span class="header-section-number">1</span> Load the Dataset</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">2</span> Feature Engineering</a></li>
  <li><a href="#traintest-split" id="toc-traintest-split" class="nav-link" data-scroll-target="#traintest-split"><span class="header-section-number">3</span> Train/Test Split</a></li>
  <li><a href="#linear-regression-get-this-model-from-lab-5.2" id="toc-linear-regression-get-this-model-from-lab-5.2" class="nav-link" data-scroll-target="#linear-regression-get-this-model-from-lab-5.2"><span class="header-section-number">4</span> Linear Regression (Get this model from Lab 5.2)</a>
  <ul class="collapse">
  <li><a href="#generalized-linear-regression-summary" id="toc-generalized-linear-regression-summary" class="nav-link" data-scroll-target="#generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</a></li>
  </ul></li>
  <li><a href="#polymnomial-regression" id="toc-polymnomial-regression" class="nav-link" data-scroll-target="#polymnomial-regression"><span class="header-section-number">5</span> Polymnomial Regression</a>
  <ul class="collapse">
  <li><a href="#polynomial-regression-summary" id="toc-polynomial-regression-summary" class="nav-link" data-scroll-target="#polynomial-regression-summary"><span class="header-section-number">5.1</span> Polynomial Regression Summary</a></li>
  </ul></li>
  <li><a href="#random-forest-regressor" id="toc-random-forest-regressor" class="nav-link" data-scroll-target="#random-forest-regressor"><span class="header-section-number">6</span> Random Forest Regressor</a>
  <ul class="collapse">
  <li><a href="#feature-importance-plot" id="toc-feature-importance-plot" class="nav-link" data-scroll-target="#feature-importance-plot"><span class="header-section-number">6.1</span> Feature Importance Plot</a></li>
  </ul></li>
  <li><a href="#compare-3-models-glr-polynomial-rf" id="toc-compare-3-models-glr-polynomial-rf" class="nav-link" data-scroll-target="#compare-3-models-glr-polynomial-rf"><span class="header-section-number">7</span> Compare 3 Models – GLR, Polynomial, RF</a>
  <ul class="collapse">
  <li><a href="#calculating-log-likelihood-and-bic-for-pyspark-models" id="toc-calculating-log-likelihood-and-bic-for-pyspark-models" class="nav-link" data-scroll-target="#calculating-log-likelihood-and-bic-for-pyspark-models"><span class="header-section-number">7.1</span> Calculating Log-Likelihood and BIC for PySpark Models</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics"><span class="header-section-number">7.2</span> Evaluation Metrics</a></li>
  </ul></li>
  <li><a href="#submission" id="toc-submission" class="nav-link" data-scroll-target="#submission">Submission</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 3: Machine Learning on Scale</h1>
<p class="subtitle lead">Causal and Predictive Analytics in Spark</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 17, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 30, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="important-reminder" class="level1 unnumbered">
<h1 class="unnumbered">Important Reminder</h1>
<p>All tasks for this lab must be performed on your <strong>AWS EC2 instance</strong>. Ensure you are connected to your instance before proceeding. You can connect in one of the following ways:</p>
<ul>
<li><span class="bloodred-bold">If you are your friend’s code make sure to put their and your name on your document</span>. Failure to do so will result in a <strong>zero</strong> for both.</li>
<li><span class="uublue-bold">Use lab 8 as it is for the regression part of the assignment</span></li>
<li>The document contains partial code snippets that you need to complete.</li>
</ul>
</section>
<section id="github-classroom-repository" class="level1 unnumbered">
<h1 class="unnumbered">GitHub Classroom Repository</h1>
<p>To complete this assignment, you must first accept the <a href="https://classroom.github.com/a/IuDBiS27"><strong>GitHub Classroom Lab 08</strong></a> request. Once accepted, follow the instructions below to clone the repository and start working.</p>
<section id="clone-the-repository-on-your-ec2-instance" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="clone-the-repository-on-your-ec2-instance">Clone the Repository on Your EC2 Instance</h2>
<section id="option-1-using-terminal" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="option-1-using-terminal">Option 1: Using Terminal</h3>
<ol type="1">
<li><p>Open your terminal in <strong>VS Code</strong>.</p></li>
<li><p>Clone the repository:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> YOUR_REPO_NAME</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>Ensure all work is performed inside this cloned directory.</p></li>
</ol>
</section>
<section id="option-2-using-vs-code-git-source-control" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="option-2-using-vs-code-git-source-control">Option 2: Using VS Code Git Source Control</h3>
<ol type="1">
<li>Open <strong>Visual Studio Code</strong>.</li>
<li>Click on the <strong>Source Control</strong> tab on the left panel.</li>
<li>Click on <strong>Clone Repository</strong>.</li>
<li>Paste the repository URL: <code>https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git</code>.</li>
<li>Select a local directory where you want to store the repository.</li>
<li>Once cloned, open the folder in VS Code and start working within it.</li>
</ol>
</section>
</section>
</section>
<section id="objectives" class="level1 unnumbered">
<h1 class="unnumbered">Objectives</h1>
<ol type="1">
<li>Use <strong>PySpark</strong> to process the Lightcast dataset.</li>
<li>Engineer features from structured columns for salary prediction.</li>
<li>Train <strong>Linear Regression model</strong>.</li>
<li>Evaluate models using <strong>RMSE</strong> and <strong>R²</strong>.</li>
<li>Visualize predictions using diagnostic plots.</li>
<li>Push work to GitHub and submit the repository link.</li>
</ol>
</section>
<section id="setup" class="level1 unnumbered">
<h1 class="unnumbered">Setup</h1>
<p>The instruction below provides you with general keywords for columns used in the lightcast file. See the data schema generated after the load dataset code above to use proper column name. For visualizations, tables, or summaries, please <strong>customize colors, fonts, and styles</strong> as appropriate to avoid a <strong>2.5-point deduction</strong>. Also, <strong>provide a two-sentence explanation</strong> describing key insights drawn from each section’s code and outputs.</p>
<ol type="1">
<li>Follow the steps below as necessary, use your best judgement in importing/installing/creating/saving files as needed.</li>
<li>Create a new Jupyter Notebook in your <code>ad688-sp25-lab08</code> directory named <code>lab08_yourname.ipynb</code>, if the file exists make sure to change the name.</li>
<li>Use your <strong>EC2 instance</strong> for this lab.</li>
<li>Ensure the <code>lightcast_data.csv</code> file is available on the EC2 instance. if not then <strong>Download the dataset</strong></li>
<li><strong>Add the dataset to <code>.gitignore</code></strong> to avoid pushing large files to GitHub. Open your <code>.gitignore</code> file and add:</li>
<li>Make sure to create a virtual environment and install the required Python libraries if needed, don’t forget to activate it:</li>
<li>Install the required Python libraries if needed, you can also use the given requirement file to install the packages to the virtual environment:</li>
</ol>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="ex">gdown</span> https://drive.google.com/uc<span class="pp">?</span>id=1V2GCHGt2dkFGqVBeoUFckU4IhUgk4ocQ</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"lightcast_job_postings.csv"</span> <span class="op">&gt;&gt;</span> .gitignore</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="load-the-dataset" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Load the Dataset</h1>
<ol type="1">
<li><strong>Load the Raw Dataset</strong>:
<ul>
<li>Use Pyspark to the <code>lightcast_data.csv</code> file into a DataFrame:</li>
<li>You can reuse the previous code.</li>
<li><span class="bloodred-bold">Copying code from your friend constitutes plagiarism. DO NOT DO THIS</span>.</li>
</ul></li>
</ol>
<div id="cell-1" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.io <span class="im">as</span> pio</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>pio.renderers.default <span class="op">=</span> <span class="st">"notebook"</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize Spark Session</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.appName(<span class="st">"LightcastData"</span>).getOrCreate()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Data</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> spark.read.option(<span class="st">"header"</span>, <span class="st">"true"</span>).option(<span class="st">"inferSchema"</span>, <span class="st">"true"</span>).option(<span class="st">"multiLine"</span>,<span class="st">"true"</span>).option(<span class="st">"escape"</span>, <span class="st">"</span><span class="ch">\"</span><span class="st">"</span>).csv(<span class="st">"./data/lightcast_job_postings.csv"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Show Schema and Sample Data</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co"># df.printSchema() </span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># df.show(5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/04/23 02:18:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
                                                                                </code></pre>
</div>
</div>
</section>
<section id="feature-engineering" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Feature Engineering</h1>
<p>Feature Engineering is a crucial step in preparing your data for machine learning. In this lab, we will focus on the following tasks:</p>
<ol type="1">
<li><strong>Drop rows with missing values</strong> in the target variable and key features.</li>
<li>By now you are already familiar with the code and the data. Based on your understanding please choose any 3 (my code output has 10) variables as:
<ol type="1">
<li>three continuous variables and, <code>MIN_YEARS_EXPERIENCE</code> (total 4, use your best judgment!)</li>
<li>two categorical .</li>
<li>Your dependent variable (y) is <code>SALARY</code>.</li>
</ol></li>
<li><strong>Convert categorical variables</strong> into numerical representations using <strong>StringIndexer</strong> and <strong>OneHotEncoder</strong>.</li>
<li><strong>Assemble features</strong> into a single vector using <strong>VectorAssembler</strong>.</li>
<li><strong>Split the data</strong> into training and testing sets.</li>
<li>You can use pipeline to do the above steps in one go.</li>
<li>Create a new column <code>MIN_YEARS_EXPERIENCE_SQ</code> by squaring the <code>MIN_YEARS_EXPERIENCE</code> column.</li>
<li>Assemble the polynomial features into a new vector column <code>features_poly</code> using <strong>VectorAssembler</strong>.</li>
<li>Show the final structure of the DataFrame with the new features.</li>
</ol>
<div id="cell-3" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, <span class="bu">pow</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> StringIndexer, OneHotEncoder, VectorAssembler</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml <span class="im">import</span> Pipeline</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with NA values in relevant columns </span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'DURATION'</span>, <span class="st">'MODELED_DURATION'</span>, <span class="st">'MIN_YEARS_EXPERIENCE'</span>, <span class="st">'MAX_YEARS_EXPERIENCE'</span>, </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'EMPLOYMENT_TYPE_NAME'</span>, <span class="st">'LOT_V6_OCCUPATION_NAME'</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'SALARY'</span>])</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Pick 3 continuous, MIN_YEARS_EXPERIENCE and 2 categorical columns</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Categorical columns</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="op">=</span> [<span class="st">'EMPLOYMENT_TYPE_NAME'</span>, <span class="st">'LOT_V6_OCCUPATION_NAME'</span>] <span class="co"># separate the categorical columns here for one hot encoding</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>continuous_cols <span class="op">=</span> [<span class="st">'DURATION'</span>, <span class="st">'MODELED_DURATION'</span>, <span class="st">'MIN_YEARS_EXPERIENCE'</span>, <span class="st">'MAX_YEARS_EXPERIENCE'</span>] </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Index and One-Hot Encode</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>indexers <span class="op">=</span> [StringIndexer(inputCol<span class="op">=</span>col, outputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_idx"</span>, handleInvalid<span class="op">=</span><span class="st">'skip'</span>) <span class="cf">for</span> col <span class="kw">in</span> categorical_cols]</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>encoders <span class="op">=</span> [OneHotEncoder(inputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_idx"</span>, outputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span>) <span class="cf">for</span> col <span class="kw">in</span> categorical_cols]</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Assemble base features (for GLR and Random Forest)</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>continuous_cols <span class="co"># continuous column names here</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> [<span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span> <span class="cf">for</span> col <span class="kw">in</span> categorical_cols], <span class="co"># columns from OneHotEncoder here</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features"</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Build pipeline and transform</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> Pipeline(stages<span class="op">=</span>indexers <span class="op">+</span> encoders <span class="op">+</span> [assembler]) <span class="co"># Create a pipeline to index, encode and assemble features</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pipeline.fit(df).transform(df)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Create squared term for Polynomial Regression</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data.withColumn(<span class="st">'MIN_YEARS_EXPERIENCE_SQ'</span>, <span class="bu">pow</span>(col(<span class="st">'MIN_YEARS_EXPERIENCE'</span>), <span class="dv">2</span>))</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Assemble polynomial features</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>assembler_poly <span class="op">=</span> VectorAssembler(</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>continuous_cols <span class="op">+</span> [<span class="st">'MIN_YEARS_EXPERIENCE_SQ'</span>] <span class="co"># continuous column + polynomial names here</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> [<span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span> <span class="cf">for</span> col <span class="kw">in</span> categorical_cols], <span class="co"># columns from OneHotEncoder here</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features_poly"</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> assembler_poly.transform(data)</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Show final structure</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>data.select(<span class="st">"SALARY"</span>, <span class="st">"features"</span>, <span class="st">"features_poly"</span>).show(<span class="dv">5</span>, truncate<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+------+----------------------------------------------+---------------------------------------------------+
|SALARY|features                                      |features_poly                                      |
+------+----------------------------------------------+---------------------------------------------------+
|131100|(11,[0,1,2,3,4,8],[11.0,11.0,2.0,2.0,1.0,1.0])|[11.0,11.0,2.0,2.0,4.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0]|
|136950|(11,[0,1,2,3,4,8],[28.0,28.0,3.0,3.0,1.0,1.0])|[28.0,28.0,3.0,3.0,9.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0]|
|136950|(11,[0,1,2,3,4,8],[28.0,28.0,3.0,3.0,1.0,1.0])|[28.0,28.0,3.0,3.0,9.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0]|
|104000|(11,[0,1,2,3,4,7],[8.0,8.0,3.0,3.0,1.0,1.0])  |[8.0,8.0,3.0,3.0,9.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0]  |
|80000 |(11,[0,1,2,3,4,9],[37.0,37.0,3.0,3.0,1.0,1.0])|[37.0,37.0,3.0,3.0,9.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0]|
+------+----------------------------------------------+---------------------------------------------------+
only showing top 5 rows
</code></pre>
</div>
</div>
</section>
<section id="traintest-split" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Train/Test Split</h1>
<ul>
<li>Perform a <strong>random split</strong> of the data into training and testing sets.</li>
<li>Set a random seed for reproducibility.</li>
<li>You can choose a number for splitting to your liking, justify your choice.</li>
</ul>
<div id="cell-5" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>train_data, test_data <span class="op">=</span> data.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">688</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((train_data.count(), <span class="bu">len</span>(train_data.columns)))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((test_data.count(), <span class="bu">len</span>(test_data.columns)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>25/04/23 02:19:45 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
                                                                                [Stage 19:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(1567, 138)
(361, 138)</code></pre>
</div>
</div>
</section>
<section id="linear-regression-get-this-model-from-lab-5.2" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Linear Regression (Get this model from Lab 5.2)</h1>
<ul>
<li>Train a <strong>Linear Regression</strong> model using the training data. <span class="uured-bold">This model is from Lab 5.2 with 3 more added features</span></li>
<li>Make sure to use the <code>features</code> column from the assembled data frame to fit the model.</li>
<li><span class="bloodred-bold">You will run in to an important issue here. Please make an effort in figuring it by yourself. This is one of the most asked interview questions in CapitalOne’s management recruiting program.</span></li>
<li>Evaluate the model on the test data.</li>
<li>Print the coefficients, intercept, R², RMSE, and MAE.</li>
<li>Use the <code>summary</code> object to extract the coefficients and their standard errors, t-values, and p-values.</li>
<li>Create a DataFrame to display the coefficients, standard errors, t-values, p-values, and confidence intervals.</li>
<li>Interpret the coefficients and their significance and explain the model performance metrics.</li>
</ul>
<div id="cell-7" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> LinearRegression</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tabulate <span class="im">import</span> tabulate</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>train_data <span class="op">=</span> train_data.withColumn(<span class="st">"SALARY"</span>, col(<span class="st">"SALARY"</span>).cast(<span class="st">"double"</span>))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>test_data <span class="op">=</span> test_data.withColumn(<span class="st">"SALARY"</span>, col(<span class="st">"SALARY"</span>).cast(<span class="st">"double"</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>feature_names_lr <span class="op">=</span> assembler.getInputCols()</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression(featuresCol<span class="op">=</span><span class="st">"features"</span>, labelCol<span class="op">=</span><span class="st">"SALARY"</span>, regParam<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>lr_model <span class="op">=</span> lr.fit(train_data)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> lr_model.summary</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>test_results_lr <span class="op">=</span> lr_model.evaluate(test_data)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients and Intercept</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Intercept: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(lr_model.intercept))</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coefficients:"</span>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, coef <span class="kw">in</span> <span class="bu">enumerate</span>(lr_model.coefficients):</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>     <span class="bu">print</span>(<span class="ss">f"  Feature </span><span class="sc">{</span>i <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>coef<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Model Evaluation</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"R² on test data: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(test_results_lr.r2))</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"RMSE on test data: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(test_results_lr.rootMeanSquaredError))</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MAE on test data: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(test_results_lr.meanAbsoluteError))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 24:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept: 89368.6358
Coefficients:
  Feature 1: -100.3177
  Feature 2: 140.7146
  Feature 3: 3403.7721
  Feature 4: 3403.7721
  Feature 5: -11808.3291
  Feature 6: -22928.0227
  Feature 7: -4754.1446
  Feature 8: 10074.2613
  Feature 9: 34763.6306
  Feature 10: -13628.4302
  Feature 11: -17691.4635
R² on test data: 0.4731
RMSE on test data: 24622.9188
MAE on test data: 18493.2211</code></pre>
</div>
</div>
<div id="cell-8" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the coefficient table</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>coefs_lr <span class="op">=</span> [lr_model.intercept] <span class="op">+</span> <span class="bu">list</span>(lr_model.coefficients)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>se_lr <span class="op">=</span> <span class="bu">list</span>(summary.coefficientStandardErrors)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>tvals_lr <span class="op">=</span> <span class="bu">list</span>(summary.tValues)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>pvals_lr <span class="op">=</span> <span class="bu">list</span>(summary.pValues)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>ci_low_lr <span class="op">=</span> [c <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> s <span class="cf">for</span> c, s <span class="kw">in</span> <span class="bu">zip</span>(coefs_lr, se_lr)]</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>ci_high_lr <span class="op">=</span> [c <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> s <span class="cf">for</span> c, s <span class="kw">in</span> <span class="bu">zip</span>(coefs_lr, se_lr)]</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>features_lr <span class="op">=</span> [<span class="st">"Intercept"</span>] <span class="op">+</span>  [<span class="ss">f"Feature_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(coefs_lr))]</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>pipeline_model <span class="op">=</span> pipeline.fit(df)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>indexer1_model <span class="op">=</span> pipeline_model.stages[<span class="dv">0</span>]</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>categories1 <span class="op">=</span> indexer1_model.labels</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>indexer2_model <span class="op">=</span> pipeline_model.stages[<span class="dv">1</span>]</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>categories2 <span class="op">=</span> indexer2_model.labels</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>encoded_categories1 <span class="op">=</span> categories1[:<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>encoded_feature_names1 <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>categorical_cols[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">=</span><span class="sc">{</span>cat<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> cat <span class="kw">in</span> encoded_categories1]</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>encoded_categories2 <span class="op">=</span> categories2[:<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>encoded_feature_names2 <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>categorical_cols[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">=</span><span class="sc">{</span>cat<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> cat <span class="kw">in</span> encoded_categories2]</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>feature_names <span class="op">=</span> [<span class="st">"Intercept"</span>] <span class="op">+</span> continuous_cols <span class="op">+</span> encoded_feature_names1 <span class="op">+</span> encoded_feature_names2</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---This is Diagnostic check, No need to print it in the final doc---")</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of features:", len(feature_names))</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of coefs:", len(coefs_lr))</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of se:", len(se_lr))</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of tvals:", len(tvals_lr))</span></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of pvals:", len(pvals_lr))</span></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>coef_table_lr <span class="op">=</span> pd.DataFrame({</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: feature_names,</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate"</span>: [<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> c <span class="kw">in</span> coefs_lr],</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Std Error"</span>: [<span class="ss">f"</span><span class="sc">{</span>s<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> s <span class="kw">in</span> se_lr],</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"t-stat"</span>: [<span class="ss">f"</span><span class="sc">{</span>t<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> t <span class="kw">in</span> tvals_lr],</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"p-Value"</span>: [<span class="ss">f"</span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> p <span class="kw">in</span> pvals_lr],</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CI Lower"</span>: [<span class="ss">f"</span><span class="sc">{</span>cl<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> cl <span class="kw">in</span> ci_low_lr],</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CI Upper"</span>: [<span class="ss">f"</span><span class="sc">{</span>ch<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> ch <span class="kw">in</span> ci_high_lr]</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabulate(coef_table_lr, headers<span class="op">=</span><span class="st">"keys"</span>, tablefmt<span class="op">=</span><span class="st">"pretty"</span>))</span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a>coef_table_lr.to_csv(<span class="st">"_output/lr_summary_pretty.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+----+---------------------------------------------------------------------------------------------+-------------+-------------+---------+---------+--------------+-------------+
|    |                                           Feature                                           |  Estimate   |  Std Error  | t-stat  | p-Value |   CI Lower   |  CI Upper   |
+----+---------------------------------------------------------------------------------------------+-------------+-------------+---------+---------+--------------+-------------+
| 0  |                                          Intercept                                          | 89368.6358  |   75.9876   | -1.3202 | 0.1870  |  89219.7001  | 89517.5715  |
| 1  |                                          DURATION                                           |  -100.3177  |   85.1881   | 1.6518  | 0.0988  |  -267.2863   |   66.6509   |
| 2  |                                      MODELED_DURATION                                       |  140.7146   | 114995.0922 | 0.0296  | 0.9764  | -225249.6661 | 225531.0954 |
| 3  |                                    MIN_YEARS_EXPERIENCE                                     |  3403.7721  | 114995.0922 | 0.0296  | 0.9764  | -221986.6086 | 228794.1529 |
| 4  |                                    MAX_YEARS_EXPERIENCE                                     |  3403.7721  |  8791.1729  | -1.3432 | 0.1794  | -13826.9268  | 20634.4710  |
| 5  |                         EMPLOYMENT_TYPE_NAME=Full-time (&gt; 32 hours)                         | -11808.3291 |  9653.1856  | -2.3752 | 0.0177  | -30728.5727  |  7111.9146  |
| 6  |                         EMPLOYMENT_TYPE_NAME=Part-time (≤ 32 hours)                         | -22928.0227 | 18580.0443  | -0.2559 | 0.7981  | -59344.9094  | 13488.8641  |
| 7  |                      LOT_V6_OCCUPATION_NAME=Data / Data Mining Analyst                      | -4754.1446  | 18577.8018  | 0.5423  | 0.5877  | -41166.6361  | 31658.3468  |
| 8  |                    LOT_V6_OCCUPATION_NAME=Business Intelligence Analyst                     | 10074.2613  | 18689.2790  | 1.8601  | 0.0631  | -26556.7255  | 46705.2480  |
| 9  |                LOT_V6_OCCUPATION_NAME=Computer Systems Engineer / Architect                 | 34763.6306  | 18718.8853  | -0.7281 | 0.4667  |  -1925.3846  | 71452.6458  |
| 10 |                    LOT_V6_OCCUPATION_NAME=Business / Management Analyst                     | -13628.4302 | 21954.1143  | -0.8058 | 0.4205  | -56658.4943  | 29401.6338  |
| 11 | LOT_V6_OCCUPATION_NAME=Clinical Analyst / Clinical Documentation and Improvement Specialist | -17691.4635 | 20555.4945  | 4.3477  | 0.0000  | -57980.2327  | 22597.3058  |
+----+---------------------------------------------------------------------------------------------+-------------+-------------+---------+---------+--------------+-------------+</code></pre>
</div>
</div>
<p>The <code>Intercept</code> is the baseline salary when all features are zero or at reference levels. This doesn’t have statistical significance. The coefficient of feature <code>DURATION</code> shows that for each additional unit of duration, salary decreases by about $100, though this isn’t statistically significant. <code>MODELED_DURATION</code>, <code>MIN_YEARS_EXPERIENCE</code> and <code>MAX_YEARS_EXPERIENCE</code> variables show positive relationships with salary but aren’t statistically significant.</p>
<p>Feature <code>Part-time employment</code> is not significant in this model, which implies nearly no effect of being part-time vs.&nbsp;reference category (mix type). On the other hand, feature <code>Full-time employment</code> is significant. Full-time jobs pay about $22.9K less than the reference category, which is an unexpected finding. Most occupational categories aren’t statistically significant. <code>Clinical Analyst</code> is the only occupation with statistical significance (p=0.0000), associated with approximately $17.7K lower salary compared to the reference category.</p>
<p>The <code>R-Squared</code> of this model shows that it explains about 47.31% of the variance in salary. This model has moderate explanatory power, suggesting other important predictors are missing or salary is inherently noisy. The <code>RMSE</code> shows that, on average, the model’s predictions deviate from actual values by about $24.6K. This is relatively high, depending on the salary scale of this dataset. The <code>MAE</code> value shows that the average absolute difference between predicted and actual salaries is about $18.5K, indicating substantial prediction error. These error metrics suggest that while the model captures some patterns, there’s still substantial variability in salaries not explained by these features. Additional predictors or different modeling approaches might be beneficial to improve prediction accuracy.</p>
<section id="generalized-linear-regression-summary" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</h2>
<p>The summary of the Generalized Linear Regression model provides important insights into the model’s performance and the significance of each feature. The coefficients indicate the relationship between each feature and the target variable (salary), while the standard errors, t-values, and p-values help assess the reliability of these estimates.</p>
<ul>
<li>Please interpret them in the context of your data and model.</li>
<li>Feature Names are purposefully not printed in the output. You can use the <code>features</code> variable to print them out.</li>
</ul>
<div id="cell-11" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> GeneralizedLinearRegression</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>glr <span class="op">=</span> GeneralizedLinearRegression(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">"features"</span>, <span class="co"># set the features column name here,</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>, <span class="co"># set the label column name here,</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span><span class="st">"gaussian"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    link<span class="op">=</span><span class="st">"identity"</span>,  <span class="co"># standard linear regression</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    maxIter<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    regParam<span class="op">=</span><span class="fl">0.3</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>glr_model <span class="op">=</span> glr.fit(train_data)<span class="co"># fit the model here</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>summary_glr <span class="op">=</span> glr_model.summary</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull feature names directly from Java backend</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>feature_names_glr <span class="op">=</span> summary_glr._call_java(<span class="st">"featureNames"</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct full table including intercept</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>features_glr <span class="op">=</span> [<span class="st">"Intercept"</span>] <span class="op">+</span> feature_names_glr <span class="co"># add an empty column for intercept with features here</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>coefs_glr <span class="op">=</span> [glr_model.intercept] <span class="op">+</span> <span class="bu">list</span>(glr_model.coefficients) <span class="co"># combine intercept with coefficients here</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>se_glr <span class="op">=</span> <span class="bu">list</span>(summary_glr.coefficientStandardErrors) <span class="co"># list standard errors here</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>tvals_glr <span class="op">=</span> <span class="bu">list</span>(summary_glr.tValues) <span class="co"># list t-values here</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>pvals_glr <span class="op">=</span> <span class="bu">list</span>(summary_glr.pValues) <span class="co"># list t-values here</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---This is Diagnostic check, No need to print it in the final doc---")</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---The numbers below should all be same---")</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---If not then adjust the array above---")</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of features:", len(features_glr))</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of coefs:", len(coefs_glr))</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of se:", len(se_glr))</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of tvals:", len(tvals_glr))</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of pvals:", len(pvals_glr))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<div id="cell-12" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tabulate <span class="im">import</span> tabulate</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> HTML</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>coef_table_glr <span class="op">=</span> pd.DataFrame({</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: features_glr,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> coefs_glr],</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Std Error"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> se_glr],</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"t-stat"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> tvals_glr],</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P-Value"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> pvals_glr]</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>coef_table_glr.to_csv(<span class="st">"_output/glr_summary.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>HTML(coef_table_glr.to_html())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Feature</th>
<th data-quarto-table-cell-role="th">Estimate</th>
<th data-quarto-table-cell-role="th">Std Error</th>
<th data-quarto-table-cell-role="th">t-stat</th>
<th data-quarto-table-cell-role="th">P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>89379.1833</td>
<td>75.9866</td>
<td>-1.3202</td>
<td>0.1870</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>DURATION</td>
<td>-100.3138</td>
<td>85.1870</td>
<td>1.6518</td>
<td>0.0988</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>MODELED_DURATION</td>
<td>140.7113</td>
<td>66392.5537</td>
<td>0.0513</td>
<td>0.9591</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>MIN_YEARS_EXPERIENCE</td>
<td>3403.7624</td>
<td>66392.5537</td>
<td>0.0513</td>
<td>0.9591</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>MAX_YEARS_EXPERIENCE</td>
<td>3403.7624</td>
<td>8790.9144</td>
<td>-1.3431</td>
<td>0.1794</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>EMPLOYMENT_TYPE_NAME_vec_Full-time (&gt; 32 hours)</td>
<td>-11807.2847</td>
<td>9652.9016</td>
<td>-2.3751</td>
<td>0.0177</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>EMPLOYMENT_TYPE_NAME_vec_Part-time (≤ 32 hours)</td>
<td>-22926.8109</td>
<td>18554.2395</td>
<td>-0.2569</td>
<td>0.7973</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Data / Data Mining Analyst</td>
<td>-4765.6821</td>
<td>18552.0159</td>
<td>0.5424</td>
<td>0.5876</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Business Intelligence Analyst</td>
<td>10062.6876</td>
<td>18663.6280</td>
<td>1.8620</td>
<td>0.0628</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Computer Systems Engineer / Architect</td>
<td>34751.9269</td>
<td>18693.1924</td>
<td>-0.7297</td>
<td>0.4657</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Business / Management Analyst</td>
<td>-13639.9180</td>
<td>21932.2377</td>
<td>-0.8072</td>
<td>0.4197</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Clinical Analyst / Clinical Documentation and Improvement Specialist</td>
<td>-17702.9232</td>
<td>20532.1169</td>
<td>4.3531</td>
<td>0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="polymnomial-regression" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Polymnomial Regression</h1>
<ul>
<li>Train a <strong>Polynomial Linear Regression</strong> model using the training data.</li>
<li>Make sure to use the <code>features_poly</code> column from the assembled data frame to fit the model.</li>
<li><span class="bloodred-bold">You will run in to an important issue here. Please make an effort in figuring it by yourself. This is one of the most asked interview questions in CapitalOne’s management recruiting program.</span></li>
<li>Evaluate the model on the test data.</li>
<li>Print the coefficients, intercept, R², RMSE, and MAE.</li>
<li>Use the <code>summary</code> object to extract the coefficients and their standard errors, t-values, and p-values.</li>
<li>Create a DataFrame to display the coefficients, standard errors, t-values, p-values, and confidence intervals.</li>
<li>Interpret the coefficients and their significance and explain the model performance metrics.</li>
</ul>
<div id="cell-14" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> GeneralizedLinearRegression</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, <span class="bu">pow</span>, sqrt, <span class="bu">abs</span>, mean</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>poly_lr <span class="op">=</span> GeneralizedLinearRegression(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">"features_poly"</span>,<span class="co"># set the features_poly column name here,</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>, <span class="co"># set the label column name here,</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span><span class="st">"gaussian"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    link<span class="op">=</span><span class="st">"identity"</span>,  <span class="co"># standard linear regression</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    maxIter<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    regParam<span class="op">=</span><span class="fl">0.3</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>poly_model <span class="op">=</span> poly_lr.fit(train_data)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>poly_preds <span class="op">=</span> poly_model.transform(test_data)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>summary_poly <span class="op">=</span> poly_model.summary</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients and Intercept</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Intercept: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(poly_model.intercept))</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coefficients:"</span>)</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, coef <span class="kw">in</span> <span class="bu">enumerate</span>(poly_model.coefficients):</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>     <span class="bu">print</span>(<span class="ss">f"  Feature </span><span class="sc">{</span>i <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>coef<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate RMSE</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> poly_preds.withColumn(<span class="st">"residual"</span>, col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>))</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> predictions.select(mean(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>)).alias(<span class="st">"mse"</span>)).first()[<span class="st">"mse"</span>] <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE: </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate R²</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>mean_y <span class="op">=</span> predictions.select(mean(col(<span class="st">"SALARY"</span>))).first()[<span class="dv">0</span>]</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>tss <span class="op">=</span> predictions.select(<span class="bu">pow</span>(col(<span class="st">"SALARY"</span>) <span class="op">-</span> mean_y, <span class="dv">2</span>).alias(<span class="st">"tss"</span>)).groupBy().<span class="bu">sum</span>(<span class="st">"tss"</span>).first()[<span class="dv">0</span>]</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>rss <span class="op">=</span> predictions.select(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>).alias(<span class="st">"rss"</span>)).groupBy().<span class="bu">sum</span>(<span class="st">"rss"</span>).first()[<span class="dv">0</span>]</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> (rss <span class="op">/</span> tss)</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R²: </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MAE</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>mae <span class="op">=</span> predictions.select(mean(<span class="bu">abs</span>(col(<span class="st">"residual"</span>))).alias(<span class="st">"mae"</span>)).first()[<span class="st">"mae"</span>]</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE: </span><span class="sc">{</span>mae<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients and Intercept</span></span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract summary data</span></span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>feature_names_poly <span class="op">=</span> summary_poly._call_java(<span class="st">"featureNames"</span>)</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>poly_features <span class="op">=</span> [<span class="st">"Intercept"</span>] <span class="op">+</span> feature_names_poly <span class="co"># add an empty column for intercept with features here</span></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>poly_coefs <span class="op">=</span> [poly_model.intercept] <span class="op">+</span> <span class="bu">list</span>(poly_model.coefficients) <span class="co"># combine intercept with coefficients here</span></span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>poly_se <span class="op">=</span> <span class="bu">list</span>(summary_poly.coefficientStandardErrors) <span class="co"># list standard errors here</span></span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>poly_tvals <span class="op">=</span> <span class="bu">list</span>(summary_poly.tValues) <span class="co"># list t-values here</span></span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a>poly_pvals <span class="op">=</span> <span class="bu">list</span>(summary_poly.pValues)<span class="co"># list t-values here</span></span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagnostics</span></span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---This is Diagnostic check, No need to print it in the final doc---")</span></span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---The numbers below should all be same---")</span></span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---If not then adjust the array above---")</span></span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of features:", len(poly_features))</span></span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of coefs:", len(poly_coefs))</span></span>
<span id="cb20-55"><a href="#cb20-55" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of se:", len(poly_se))</span></span>
<span id="cb20-56"><a href="#cb20-56" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of tvals:", len(poly_tvals))</span></span>
<span id="cb20-57"><a href="#cb20-57" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of pvals:", len(poly_pvals))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                                                                                                                                                                                                                                                                                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept: 80026.3570
Coefficients:
  Feature 1: -64.1358
  Feature 2: 87.9631
  Feature 3: 6328.9871
  Feature 4: 6328.9871
  Feature 5: -602.0926
  Feature 6: -12487.3322
  Feature 7: -24876.9825
  Feature 8: -4314.8652
  Feature 9: 10284.2084
  Feature 10: 37290.4380
  Feature 11: -13389.2639
  Feature 12: -16018.0412
RMSE: 24425.06
R²: 0.4815
MAE: 18419.56</code></pre>
</div>
</div>
<section id="polynomial-regression-summary" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="polynomial-regression-summary"><span class="header-section-number">5.1</span> Polynomial Regression Summary</h2>
<p>The summary of the Generalized Linear Regression model provides important insights into the model’s performance and the significance of each feature. The coefficients indicate the relationship between each feature and the target variable (salary), while the standard errors, t-values, and p-values help assess the reliability of these estimates.</p>
<ul>
<li>Please interpret them in the context of your data and model.</li>
<li>Feature Names are purposefully not printed in the output. You can use the <code>features</code> variable to print them out.</li>
</ul>
<div id="cell-16" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ci_low_poly <span class="op">=</span> [c <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> s <span class="cf">for</span> c, s <span class="kw">in</span> <span class="bu">zip</span>(poly_coefs, poly_se)]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ci_high_poly <span class="op">=</span> [c <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> s <span class="cf">for</span> c, s <span class="kw">in</span> <span class="bu">zip</span>(poly_coefs, poly_se)]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>poly_coef_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: poly_features,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> poly_coefs],</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Std Error"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> poly_se],</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"t-stat"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> poly_tvals],</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P-Value"</span>: [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> v <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="va">None</span> <span class="cf">for</span> v <span class="kw">in</span> poly_pvals],</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CI Lower"</span>: [<span class="ss">f"</span><span class="sc">{</span>cl<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> cl <span class="kw">in</span> ci_low_poly],</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CI Upper"</span>: [<span class="ss">f"</span><span class="sc">{</span>ch<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> ch <span class="kw">in</span> ci_high_poly]</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>poly_coef_table.to_csv(<span class="st">"_output/poly_summary.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co"># print(tabulate(poly_coef_table, headers="keys", tablefmt="pretty"))</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>HTML(poly_coef_table.to_html())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Feature</th>
<th data-quarto-table-cell-role="th">Estimate</th>
<th data-quarto-table-cell-role="th">Std Error</th>
<th data-quarto-table-cell-role="th">t-stat</th>
<th data-quarto-table-cell-role="th">P-Value</th>
<th data-quarto-table-cell-role="th">CI Lower</th>
<th data-quarto-table-cell-role="th">CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>80026.3570</td>
<td>74.9516</td>
<td>-0.8557</td>
<td>0.3923</td>
<td>79879.4519</td>
<td>80173.2620</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>DURATION</td>
<td>-64.1358</td>
<td>84.1579</td>
<td>1.0452</td>
<td>0.2961</td>
<td>-229.0854</td>
<td>100.8138</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>MODELED_DURATION</td>
<td>87.9631</td>
<td>65341.1437</td>
<td>0.0969</td>
<td>0.9228</td>
<td>-127980.6785</td>
<td>128156.6047</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>MIN_YEARS_EXPERIENCE</td>
<td>6328.9871</td>
<td>65341.1437</td>
<td>0.0969</td>
<td>0.9228</td>
<td>-121739.6545</td>
<td>134397.6287</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>MAX_YEARS_EXPERIENCE</td>
<td>6328.9871</td>
<td>83.9020</td>
<td>-7.1761</td>
<td>0.0000</td>
<td>6164.5392</td>
<td>6493.4351</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>MIN_YEARS_EXPERIENCE_SQ</td>
<td>-602.0926</td>
<td>8652.0498</td>
<td>-1.4433</td>
<td>0.1491</td>
<td>-17560.1102</td>
<td>16355.9250</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>EMPLOYMENT_TYPE_NAME_vec_Full-time (&gt; 32 hours)</td>
<td>-12487.3322</td>
<td>9503.7370</td>
<td>-2.6176</td>
<td>0.0089</td>
<td>-31114.6567</td>
<td>6139.9924</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>EMPLOYMENT_TYPE_NAME_vec_Part-time (≤ 32 hours)</td>
<td>-24876.9825</td>
<td>18260.1623</td>
<td>-0.2363</td>
<td>0.8132</td>
<td>-60666.9007</td>
<td>10912.9356</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Data / Data Mining Analyst</td>
<td>-4314.8652</td>
<td>18257.8921</td>
<td>0.5633</td>
<td>0.5733</td>
<td>-40100.3336</td>
<td>31470.6033</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Business Intelligence Analyst</td>
<td>10284.2084</td>
<td>18371.1145</td>
<td>2.0298</td>
<td>0.0425</td>
<td>-25723.1759</td>
<td>46291.5927</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Computer Systems Engineer / Architect</td>
<td>37290.4380</td>
<td>18396.8372</td>
<td>-0.7278</td>
<td>0.4668</td>
<td>1232.6371</td>
<td>73348.2389</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Business / Management Analyst</td>
<td>-13389.2639</td>
<td>21585.7699</td>
<td>-0.7421</td>
<td>0.4582</td>
<td>-55697.3729</td>
<td>28918.8451</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>LOT_V6_OCCUPATION_NAME_vec_Clinical Analyst / Clinical Documentation and Improvement Specialist</td>
<td>-16018.0412</td>
<td>20248.5602</td>
<td>3.9522</td>
<td>0.0001</td>
<td>-55705.2191</td>
<td>23669.1368</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Coefficient Interpretation</strong> - <code>Intercept</code> (80026.3570): This is the baseline salary when all other variables are at zero or reference levels. It’s not statistically significant. - <code>DURATION</code> (-64.1358) and <code>MODELED_DURATION</code> (87.9631): Neither shows statistical significance, suggesting these time-related variables don’t significantly impact salary in this model. - Experience Variables: <code>MAX_YEARS_EXPERIENCE</code> (6328.9871) is highly significant (p=0.0000), indicating that each additional year of maximum experience increases salary by about $6K. The squared term for minimum experience <code>MIN_YEARS_EXPERIENCE_SQ</code> isn’t significant, suggesting no strong non-linear relationship. - Employment Type: <code>Full-time</code> workers earn approximately $12.5K less than the reference category, and this is statistically significant (p=0.0089). <code>Part-time</code> workers show a larger negative coefficient (-24876) but it’s not statistically significant. - Occupation: <code>Business Intelligence Analyst</code> shows a significant positive effect (p=0.0425), associated with about $10.3K higher salary compared to the reference category. <code>Clinical Analyst</code> shows a highly significant negative effect (p=0.0001), with salaries about $16K lower. Other occupations don’t show statistical significance.</p>
<p><strong>Model Performance</strong></p>
<p>The <code>R-Squared</code> value shows that the polynomial model explains 48.15% of the variance in salary, slightly better than the previous linear model. The <code>RMSE</code> shows that, on average, the model’s predictions deviate from actual values by about $24.4K, which is slightly lower than the previous model though, but still high. The <code>MAE</code> value shows that the average absolute difference between predicted and actual salaries is about $18.4K, slightly improved from the previous model.</p>
</section>
</section>
<section id="random-forest-regressor" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Random Forest Regressor</h1>
<ul>
<li>Train a <strong>Random Forest Regressor</strong> model using the training data.</li>
<li>Make sure to use the <code>features</code> column from the assembled data frame to fit the model.</li>
<li>choose anywhere between 100-500 <code>trees</code> for the model.</li>
<li>choose <code>max depth</code> between 4-10.</li>
<li>remember<code>number of trees</code> and <code>max depth</code> are hyperparameters and roughly inversely proportional to each other.</li>
</ul>
<div id="cell-19" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> RandomForestRegressor</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize Random Forest</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestRegressor(featuresCol<span class="op">=</span><span class="st">"features"</span>, <span class="co"># set the features column name here,</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                           labelCol<span class="op">=</span><span class="st">"SALARY"</span>, <span class="co"># set the label column name here,</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                           numTrees<span class="op">=</span><span class="dv">200</span>, <span class="co"># number of trees</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                           maxDepth<span class="op">=</span><span class="dv">6</span>, <span class="co"># maximum depth of each tree</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                           seed<span class="op">=</span><span class="dv">688</span> <span class="co"># for reproducibility</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>                           )</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Train model</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>rf_model <span class="op">=</span> rf.fit(</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    data.select(<span class="st">"SALARY"</span>, <span class="co"># set dependent variable here</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>                <span class="st">"features"</span> <span class="co"># set features (not features_poly) here</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                ))</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate predictions</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>rf_preds <span class="op">=</span> rf_model.transform(data.select(<span class="st">"SALARY"</span>, <span class="st">"features"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>25/04/23 02:24:09 WARN DAGScheduler: Broadcasting large task binary with size 1025.9 KiB
25/04/23 02:24:10 WARN DAGScheduler: Broadcasting large task binary with size 1794.6 KiB
WARNING: An illegal reflective access operation has occurred                    
WARNING: Illegal reflective access by org.apache.spark.util.SizeEstimator$ (file:/opt/spark-3.5.4-bin-hadoop3/jars/spark-core_2.12-3.5.4.jar) to field java.nio.charset.Charset.name
WARNING: Please consider reporting this to the maintainers of org.apache.spark.util.SizeEstimator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release</code></pre>
</div>
</div>
<section id="feature-importance-plot" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="feature-importance-plot"><span class="header-section-number">6.1</span> Feature Importance Plot</h2>
<ul>
<li>Extract the feature importance from the Random Forest model and plot them using <strong>Seaborn</strong>.</li>
<li>Use a bar plot to visualize the top 10 most important features.</li>
<li>Save the plot as <code>rf_feature_importance.png</code> in the <code>output/</code> folder.</li>
</ul>
<div id="cell-21" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract feature importances</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_actual_feature_names(df, assembler, encoded_cols):</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    full_feature_names <span class="op">=</span> []</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col_name <span class="kw">in</span> assembler.getInputCols():</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> col_name <span class="kw">in</span> encoded_cols:</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>            <span class="cf">try</span>:</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>                attr_meta <span class="op">=</span> df.schema[col_name].metadata[<span class="st">'ml_attr'</span>][<span class="st">'attrs'</span>]</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> attr_group <span class="kw">in</span> attr_meta.values():</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">for</span> attr <span class="kw">in</span> attr_group:</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>                        full_feature_names.append(attr[<span class="st">'name'</span>])</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>            <span class="cf">except</span>:</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>                <span class="co"># In case metadata is missing or malformed</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>                full_feature_names.append(col_name)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>            full_feature_names.append(col_name)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> full_feature_names</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>encoded_cols <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span> <span class="cf">for</span> col <span class="kw">in</span> categorical_cols]  <span class="co"># e.g. ["EDUCATION_LEVELS_NAME_vec", ...]</span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>feature_names <span class="op">=</span> get_actual_feature_names(data, assembler, encoded_cols)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>importances <span class="op">=</span> rf_model.featureImportances.toArray() <span class="co"># add feature importances to array here</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---This is Diagnostic check, No need to print it in the final doc---")</span></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---The numbers below should all be same---")</span></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---If not then adjust the array above---")</span></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of feature names:", len(feature_names))     # should be 27</span></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of importances:", len(importances))         # should be 27</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-22" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> clean_feature_names(feature_list):</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    clean_names <span class="op">=</span> []</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name <span class="kw">in</span> feature_list:</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">isinstance</span>(name, <span class="bu">list</span>):</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>            clean_names.append(<span class="st">", "</span>.join(<span class="bu">str</span>(n) <span class="cf">for</span> n <span class="kw">in</span> name))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> <span class="bu">isinstance</span>(name, <span class="bu">str</span>) <span class="kw">and</span> name.startswith(<span class="st">"["</span>):</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>            <span class="co"># it's a stringified list</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>            clean_names.append(name.replace(<span class="st">"["</span>, <span class="st">""</span>).replace(<span class="st">"]"</span>, <span class="st">""</span>).replace(<span class="st">"'"</span>, <span class="st">""</span>).replace(<span class="st">'"'</span>, <span class="st">''</span>).strip())</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>            clean_names.append(<span class="bu">str</span>(name))</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> clean_names</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Build dataframe</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>importance_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: feature_names,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Importance"</span>: importances</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>}).sort_values(by<span class="op">=</span><span class="st">"Importance"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>importance_df[<span class="st">"Feature"</span>] <span class="op">=</span> clean_feature_names(importance_df[<span class="st">"Feature"</span>])</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>sns.barplot(</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"Importance"</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"Feature"</span>,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>importance_df,</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>    hue<span class="op">=</span><span class="st">"Feature"</span>,</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>    palette<span class="op">=</span><span class="st">"viridis"</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> textwrap</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> plt.gca().get_yticklabels()</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>new_labels <span class="op">=</span> [textwrap.fill(label.get_text(), width<span class="op">=</span><span class="dv">30</span>) <span class="cf">for</span> label <span class="kw">in</span> labels]</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>plt.yticks(<span class="bu">range</span>(<span class="bu">len</span>(new_labels)), new_labels, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>plt.xticks(fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Feature Importances from Random Forest Model"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Importance"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Feature"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/rf_feature_importance.png"</span>)</span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assignment03_files/figure-html/cell-13-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="compare-3-models-glr-polynomial-rf" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Compare 3 Models – GLR, Polynomial, RF</h1>
<ul>
<li>Generate predictions for all three models (GLR, Polynomial, RF) on the test data.</li>
<li>Calculate RMSE, and AIC, BIC, for each model. AIC is part of the model summary, while RMSE and BIC needs to be calculated.</li>
<li>Create a DataFrame to store the predictions and actual values for each model.</li>
<li>Use <strong>Seaborn</strong> to create a 2x2 grid plot comparing the actual vs.&nbsp;predicted values for each model.</li>
</ul>
<section id="calculating-log-likelihood-and-bic-for-pyspark-models" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="calculating-log-likelihood-and-bic-for-pyspark-models"><span class="header-section-number">7.1</span> Calculating Log-Likelihood and BIC for PySpark Models</h2>
<ul>
<li>Log Likelihood represents the probability of observing the data given the model parameters. It is used in AIC and BIC calculations.</li>
<li>Log Likelihood is not directly available in PySpark’s GeneralizedLinearRegression model summary. However, you can calculate it using the deviance and the number of observations.</li>
<li>The formula for Log Likelihood is: <span class="math inline">\(\text{Log Likelihood} = -\frac{1}{2} \left( n \cdot \log(2\pi) + n \cdot \log(\text{dispersion}) + \frac{\text{deviance}}{\text{dispersion}} \right)\)</span>
<ul>
<li><span class="math inline">\(n\)</span> is the number of observations</li>
<li><span class="math inline">\(\text{dispersion}\)</span> is the dispersion parameter (variance) of the model, in pyspark it is the same as the residual deviance.</li>
<li><span class="math inline">\(\text{deviance}\)</span> is the deviance of the model</li>
</ul></li>
<li>BIC is calculated as: <span class="math display">\[
\begin{align}
\text{BIC} &amp;= k \cdot \log(n) - 2 \cdot \text{Log Likelihood}\\
\text{BIC} &amp;= k \cdot \log(n) + \left( n \cdot \log(2\pi) + n \cdot \log(\text{dispersion}) + \frac{\text{deviance}}{\text{dispersion}} \right)
\end{align}
\]</span></li>
</ul>
<div id="cell-24" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, <span class="bu">pow</span>, sqrt, avg</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Evaluate all three models ---</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>evaluator_r2 <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"r2"</span>) <span class="co"># Use RegressionEvaluator to evaluate R2 here</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co"># GLR</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>glr_preds <span class="op">=</span> glr_model.transform(test_data)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>glr_residuals <span class="op">=</span> glr_preds.select(</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"SALARY"</span>),</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"prediction"</span>),</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    (col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>)).alias(<span class="st">"residual"</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>glr_r2   <span class="op">=</span> evaluator_r2.evaluate(glr_preds) <span class="co"># evaluate GLR R2 here</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>glr_rmse <span class="op">=</span> np.sqrt(glr_residuals.select(avg(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>))).first()[<span class="dv">0</span>]) <span class="co"># evaluate GLR RMSE here</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> glr_residuals.count()</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="bu">len</span>(glr_model.coefficients) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>glr_aic  <span class="op">=</span> n <span class="op">*</span> np.log(glr_residuals.select(avg(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>))).first()[<span class="dv">0</span>]) <span class="op">+</span> <span class="dv">2</span> <span class="op">*</span> p <span class="co"># calculate AIC here</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>glr_bic  <span class="op">=</span> n <span class="op">*</span> np.log(glr_residuals.select(avg(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>))).first()[<span class="dv">0</span>]) <span class="op">+</span> p <span class="op">*</span> np.log(n) <span class="co"># calculate BIC here</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>glr_pdf <span class="op">=</span> glr_residuals.select(<span class="st">"SALARY"</span>, col(<span class="st">"prediction"</span>).alias(<span class="st">"GLR"</span>)).toPandas()</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>glr_df <span class="op">=</span> pd.DataFrame({<span class="st">"SALARY"</span>: glr_pdf[<span class="st">"SALARY"</span>], <span class="st">"GLR"</span>: glr_pdf[<span class="st">"GLR"</span>]})</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Polynomial</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>poly_preds <span class="op">=</span> poly_model.transform(test_data)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>poly_residuals <span class="op">=</span> poly_preds.select(</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"SALARY"</span>),</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"prediction"</span>),</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>    (col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>)).alias(<span class="st">"residual"</span>)</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a>poly_r2   <span class="op">=</span> evaluator_r2.evaluate(poly_preds) <span class="co"># evaluate Poly GLR R2 here</span></span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>poly_rmse <span class="op">=</span> np.sqrt(poly_residuals.select(avg(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>))).first()[<span class="dv">0</span>]) <span class="co"># evaluate Poly RMSE here</span></span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>poly_aic  <span class="op">=</span> <span class="va">None</span></span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>poly_bic  <span class="op">=</span> <span class="va">None</span></span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>poly_pdf <span class="op">=</span> poly_residuals.select(<span class="st">"SALARY"</span>, col(<span class="st">"prediction"</span>).alias(<span class="st">"Polynomial"</span>)).toPandas()</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>poly_df <span class="op">=</span> pd.DataFrame({<span class="st">"SALARY"</span>: poly_pdf[<span class="st">"SALARY"</span>], <span class="st">"Polynomial"</span>: poly_pdf[<span class="st">"Polynomial"</span>]})</span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a><span class="co"># RF</span></span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a>rf_preds <span class="op">=</span> rf_model.transform(test_data)</span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a>rf_residuals <span class="op">=</span> rf_preds.select(</span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"SALARY"</span>),</span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"prediction"</span>),</span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a>    (col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>)).alias(<span class="st">"residual"</span>)</span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a>rf_r2   <span class="op">=</span> evaluator_r2.evaluate(rf_preds) <span class="co"># evaluate RF R2 here</span></span>
<span id="cb28-51"><a href="#cb28-51" aria-hidden="true" tabindex="-1"></a>rf_rmse <span class="op">=</span> np.sqrt(rf_residuals.select(avg(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>))).first()[<span class="dv">0</span>]) <span class="co"># evaluate RF RMSE here</span></span>
<span id="cb28-52"><a href="#cb28-52" aria-hidden="true" tabindex="-1"></a>rf_aic  <span class="op">=</span> <span class="va">None</span></span>
<span id="cb28-53"><a href="#cb28-53" aria-hidden="true" tabindex="-1"></a>rf_bic  <span class="op">=</span> <span class="va">None</span></span>
<span id="cb28-54"><a href="#cb28-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-55"><a href="#cb28-55" aria-hidden="true" tabindex="-1"></a>rf_pdf <span class="op">=</span> rf_residuals.select(<span class="st">"SALARY"</span>, col(<span class="st">"prediction"</span>).alias(<span class="st">"RandomForest"</span>)).toPandas()</span>
<span id="cb28-56"><a href="#cb28-56" aria-hidden="true" tabindex="-1"></a>rf_df <span class="op">=</span> pd.DataFrame({<span class="st">"SALARY"</span>: rf_pdf[<span class="st">"SALARY"</span>], <span class="st">"RandomForest"</span>: rf_pdf[<span class="st">"RandomForest"</span>]})</span>
<span id="cb28-57"><a href="#cb28-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-58"><a href="#cb28-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge for plot</span></span>
<span id="cb28-59"><a href="#cb28-59" aria-hidden="true" tabindex="-1"></a>merged <span class="op">=</span> glr_df.copy()</span>
<span id="cb28-60"><a href="#cb28-60" aria-hidden="true" tabindex="-1"></a>merged[<span class="st">"Polynomial"</span>] <span class="op">=</span> poly_df[<span class="st">"Polynomial"</span>]</span>
<span id="cb28-61"><a href="#cb28-61" aria-hidden="true" tabindex="-1"></a>merged[<span class="st">"RandomForest"</span>] <span class="op">=</span> rf_df[<span class="st">"RandomForest"</span>]</span>
<span id="cb28-62"><a href="#cb28-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-63"><a href="#cb28-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt</span></span>
<span id="cb28-64"><a href="#cb28-64" aria-hidden="true" tabindex="-1"></a>plot_df <span class="op">=</span> merged.melt(id_vars<span class="op">=</span><span class="st">"SALARY"</span>, var_name<span class="op">=</span><span class="st">"Model"</span>, value_name<span class="op">=</span><span class="st">"Predicted"</span>)</span>
<span id="cb28-65"><a href="#cb28-65" aria-hidden="true" tabindex="-1"></a>plot_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">SALARY</th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Predicted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>100807.0</td>
<td>GLR</td>
<td>80583.280341</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>75550.0</td>
<td>GLR</td>
<td>73210.191198</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>62400.0</td>
<td>GLR</td>
<td>74058.537858</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>72500.0</td>
<td>GLR</td>
<td>75203.494534</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>123850.0</td>
<td>GLR</td>
<td>142417.963584</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="evaluation-metrics" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="evaluation-metrics"><span class="header-section-number">7.2</span> Evaluation Metrics</h2>
<div id="cell-26" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">17</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>models <span class="op">=</span> {</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GLR"</span>: (glr_rmse, glr_r2, glr_aic, glr_bic),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Polynomial"</span>: (poly_rmse, poly_r2, <span class="st">"NA"</span>, <span class="st">"NA"</span>),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"RandomForest"</span>: (rf_rmse, rf_r2, <span class="st">"NA"</span>, <span class="st">"NA"</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>model_dfs <span class="op">=</span> {</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GLR"</span>: glr_df,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Polynomial"</span>: poly_df,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"RandomForest"</span>: rf_df</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> idx, (model_name, (rmse, r2, aic, bic)) <span class="kw">in</span> <span class="bu">enumerate</span>(models.items(), <span class="dv">1</span>):</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">3</span>, <span class="dv">1</span>, idx)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    model_data <span class="op">=</span> model_dfs[model_name]</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    sns.scatterplot(x<span class="op">=</span><span class="st">"SALARY"</span>, y<span class="op">=</span>model_name, data<span class="op">=</span>model_data, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span>model_name)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>    x_min <span class="op">=</span> model_data[<span class="st">"SALARY"</span>].<span class="bu">min</span>()</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>    x_max <span class="op">=</span> model_data[<span class="st">"SALARY"</span>].<span class="bu">max</span>()</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>    plt.plot([x_min, x_max], [x_min, x_max], <span class="st">'r-'</span>, label<span class="op">=</span><span class="st">"Ideal Fit"</span>)</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> aic <span class="op">!=</span> <span class="st">"NA"</span> <span class="kw">and</span> bic <span class="op">!=</span> <span class="st">"NA"</span>:</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="ss">f"</span><span class="sc">{</span>model_name<span class="sc">}</span><span class="ss"> Prediction</span><span class="ch">\n</span><span class="ss">RMSE=</span><span class="sc">{</span>rmse<span class="sc">:.1f}</span><span class="ss"> | R²=</span><span class="sc">{</span>r2<span class="sc">:.3f}</span><span class="ss"> | AIC=</span><span class="sc">{</span>aic<span class="sc">:.1f}</span><span class="ss"> | BIC=</span><span class="sc">{</span>bic<span class="sc">:.1f}</span><span class="ss">"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="ss">f"</span><span class="sc">{</span>model_name<span class="sc">}</span><span class="ss"> Prediction</span><span class="ch">\n</span><span class="ss">RMSE=</span><span class="sc">{</span>rmse<span class="sc">:.1f}</span><span class="ss"> | R²=</span><span class="sc">{</span>r2<span class="sc">:.3f}</span><span class="ss"> | AIC=NA | BIC=NA"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Actual Salary"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"Predicted Salary"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/model_comparison.png"</span>)</span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assignment03_files/figure-html/cell-15-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="submission" class="level1 unnumbered">
<h1 class="unnumbered">Submission</h1>
<ol type="1">
<li>Save figures in the <code>output/</code> folder.</li>
<li>Commit and push code and output files:</li>
</ol>
<div class="sourceCode" id="cb31"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> add .</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> commit <span class="at">-m</span> <span class="st">"Add Lab 08 Salary Prediction models and output"</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> push origin main</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="3" type="1">
<li>Submit your GitHub repository link.</li>
</ol>
</section>
<section id="resources" class="level1 unnumbered">
<h1 class="unnumbered">Resources</h1>
<ul>
<li><a href="https://spark.apache.org/docs/latest/ml-guide.html">PySpark MLlib Docs</a><br>
</li>
<li><a href="https://seaborn.pydata.org/">Seaborn Docs</a><br>
</li>
<li><a href="https://pandas.pydata.org/docs/user_guide/index.html">Pandas User Guide</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>